#
# This is mostly copied from
# https://github.com/docker/build-push-action#git-context
#
name: Build & Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    # This environment stores the DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
    # see https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    environment:
      name: dockerhub
      url: https://hub.docker.com/r/niccokunzmann/spaceapistatusimage
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        # see https://docs.docker.com/build/building/drivers/#list-available-builders
        name: Show possible platforms
        run: docker buildx ls
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,
          tags: user/app:latest